name: Build Arduino Sketch [D1 mini, SBH-20 and SJB-HS]

on:
  push:
    branches: [ master, develop ]
    paths: [ "src/**" ]
  pull_request:
    branches: [ develop ]
    paths: [ "src/**" ]
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        arduino-platform: [ "esp8266:esp8266@2.7.4" ]
        model: [ "SB-H20", "SJB-HS" ]
        include:
          - arduino-platform: "esp8266:esp8266@2.7.4"
            fqbn: "esp8266:esp8266:d1_mini:xtal=160,vt=iram,exception=enabled,ssl=basic,eesz=4M1M,ip=lm2f,dbg=Disabled,lvl=None____"
            sketch: "src/esp8266-intexsbh20/esp8266-intexsbh20.ino"
            install-options: "--additional-urls \"http://arduino.esp8266.com/stable/package_esp8266com_index.json\""
          - model: "SB-H20"
            compiler-options: "--warnings more --build-property compiler.cpp.extra_flags=\"-D MODEL_SB_H20\""
          - model: "SJB-HS"
            compiler-options: "--warnings more --build-property compiler.cpp.extra_flags=\"-D MODEL_SJB_HS\""
      max-parallel: 2

    steps:
      - name: Checkout
        uses: actions/checkout@main

      - name: Setup Arduino CLI
        uses: arduino/setup-arduino-cli@v1

      - name: Install Platform
        run: |
          arduino-cli core update-index ${{ matrix.install-options }}
          arduino-cli core install ${{ matrix.arduino-platform }} ${{ matrix.install-options }}
          arduino-cli lib install ArduinoJson@6.19.4
          arduino-cli lib install PubSubClient@2.8
      - name: Compile Sketch
        run: arduino-cli compile --fqbn ${{ matrix.fqbn }} ./${{ matrix.sketch }} ${{ matrix.compiler-options }}

    runs-on: ubuntu-latest